version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - if [ -f package-lock.json ]; then npm ci; else npm install; fi
  build:
    commands:
      - echo "Building Vite React app..."
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist




